// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearCodexConfigBackups() {
  return window['go']['main']['App']['ClearCodexConfigBackups']();
}

export function DeleteCodexConfigBackup(arg1) {
  return window['go']['main']['App']['DeleteCodexConfigBackup'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function GenerateCodexConfigToml() {
  return window['go']['main']['App']['GenerateCodexConfigToml']();
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBridgeStatus() {
  return window['go']['main']['App']['GetBridgeStatus']();
}

export function GetCodexConfigPath() {
  return window['go']['main']['App']['GetCodexConfigPath']();
}

export function GetLogHistory(arg1) {
  return window['go']['main']['App']['GetLogHistory'](arg1);
}

export function GetOverviewSnapshot() {
  return window['go']['main']['App']['GetOverviewSnapshot']();
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function ListCodexConfigBackups() {
  return window['go']['main']['App']['ListCodexConfigBackups']();
}

export function ReadCodexConfigToml() {
  return window['go']['main']['App']['ReadCodexConfigToml']();
}

export function RestartBridge() {
  return window['go']['main']['App']['RestartBridge']();
}

export function RestoreCodexConfigToml() {
  return window['go']['main']['App']['RestoreCodexConfigToml']();
}

export function RestoreCodexConfigTomlFromBackup(arg1) {
  return window['go']['main']['App']['RestoreCodexConfigTomlFromBackup'](arg1);
}

export function RunHealthCheck() {
  return window['go']['main']['App']['RunHealthCheck']();
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function StartBridge() {
  return window['go']['main']['App']['StartBridge']();
}

export function StopBridge() {
  return window['go']['main']['App']['StopBridge']();
}

export function WriteCodexConfigToml() {
  return window['go']['main']['App']['WriteCodexConfigToml']();
}

export function WriteCodexConfigTomlRaw(arg1) {
  return window['go']['main']['App']['WriteCodexConfigTomlRaw'](arg1);
}
