// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveCodexSession(arg1) {
  return window['go']['main']['App']['ArchiveCodexSession'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearCodexConfigBackups() {
  return window['go']['main']['App']['ClearCodexConfigBackups']();
}

export function CountLegacySessions() {
  return window['go']['main']['App']['CountLegacySessions']();
}

export function DeleteCodexConfigBackup(arg1) {
  return window['go']['main']['App']['DeleteCodexConfigBackup'](arg1);
}

export function DeleteCodexSession(arg1) {
  return window['go']['main']['App']['DeleteCodexSession'](arg1);
}

export function DeleteCodexSessionBackup(arg1) {
  return window['go']['main']['App']['DeleteCodexSessionBackup'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function GenerateCodexConfigToml() {
  return window['go']['main']['App']['GenerateCodexConfigToml']();
}

export function GenerateCodexConfigTomlProfiles() {
  return window['go']['main']['App']['GenerateCodexConfigTomlProfiles']();
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCodexConfigPath() {
  return window['go']['main']['App']['GetCodexConfigPath']();
}

export function GetCodexSessionContent(arg1) {
  return window['go']['main']['App']['GetCodexSessionContent'](arg1);
}

export function GetDebugMode() {
  return window['go']['main']['App']['GetDebugMode']();
}

export function GetLogHistory(arg1) {
  return window['go']['main']['App']['GetLogHistory'](arg1);
}

export function GetOverviewSnapshot() {
  return window['go']['main']['App']['GetOverviewSnapshot']();
}

export function GetOverviewSnapshotForSource(arg1) {
  return window['go']['main']['App']['GetOverviewSnapshotForSource'](arg1);
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetProxyStatusForSource(arg1) {
  return window['go']['main']['App']['GetProxyStatusForSource'](arg1);
}

export function GetSandboxConfig() {
  return window['go']['main']['App']['GetSandboxConfig']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetUsageBalance(arg1) {
  return window['go']['main']['App']['GetUsageBalance'](arg1);
}

export function GetUsageStats() {
  return window['go']['main']['App']['GetUsageStats']();
}

export function HasLegacySessions() {
  return window['go']['main']['App']['HasLegacySessions']();
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function ListCodexConfigBackups() {
  return window['go']['main']['App']['ListCodexConfigBackups']();
}

export function ListCodexSessionBackups() {
  return window['go']['main']['App']['ListCodexSessionBackups']();
}

export function ListCodexSessionProviders() {
  return window['go']['main']['App']['ListCodexSessionProviders']();
}

export function ListCodexSessions() {
  return window['go']['main']['App']['ListCodexSessions']();
}

export function MigrateCodexProviders(arg1, arg2) {
  return window['go']['main']['App']['MigrateCodexProviders'](arg1, arg2);
}

export function MigrateSingleCodexSession(arg1, arg2) {
  return window['go']['main']['App']['MigrateSingleCodexSession'](arg1, arg2);
}

export function PluginUnlockLogin() {
  return window['go']['main']['App']['PluginUnlockLogin']();
}

export function ReadCodexConfigToml() {
  return window['go']['main']['App']['ReadCodexConfigToml']();
}

export function RestartProxy() {
  return window['go']['main']['App']['RestartProxy']();
}

export function RestartProxyForSource(arg1) {
  return window['go']['main']['App']['RestartProxyForSource'](arg1);
}

export function RestoreCodexConfigToml() {
  return window['go']['main']['App']['RestoreCodexConfigToml']();
}

export function RestoreCodexConfigTomlFromBackup(arg1) {
  return window['go']['main']['App']['RestoreCodexConfigTomlFromBackup'](arg1);
}

export function RestoreCodexSessions(arg1) {
  return window['go']['main']['App']['RestoreCodexSessions'](arg1);
}

export function RunHealthCheck() {
  return window['go']['main']['App']['RunHealthCheck']();
}

export function RunHealthCheckForSource(arg1) {
  return window['go']['main']['App']['RunHealthCheckForSource'](arg1);
}

export function RunSync(arg1) {
  return window['go']['main']['App']['RunSync'](arg1);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SetCurrentProfile(arg1) {
  return window['go']['main']['App']['SetCurrentProfile'](arg1);
}

export function SetDebugMode(arg1) {
  return window['go']['main']['App']['SetDebugMode'](arg1);
}

export function SetSandboxConfig(arg1) {
  return window['go']['main']['App']['SetSandboxConfig'](arg1);
}

export function ShouldHideOnClose() {
  return window['go']['main']['App']['ShouldHideOnClose']();
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StartProxyForSource(arg1) {
  return window['go']['main']['App']['StartProxyForSource'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function StopProxyForSource(arg1) {
  return window['go']['main']['App']['StopProxyForSource'](arg1);
}

export function WriteCodexConfigToml() {
  return window['go']['main']['App']['WriteCodexConfigToml']();
}

export function WriteCodexConfigTomlProfiles() {
  return window['go']['main']['App']['WriteCodexConfigTomlProfiles']();
}

export function WriteCodexConfigTomlRaw(arg1) {
  return window['go']['main']['App']['WriteCodexConfigTomlRaw'](arg1);
}
