// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ArchiveCodexSession(arg1:string):Promise<main.CodexSession>;

export function CheckForUpdates():Promise<main.UpdateCheckResult>;

export function ClearCodexConfigBackups():Promise<number>;

export function CountLegacySessions():Promise<number>;

export function DeleteCodexConfigBackup(arg1:string):Promise<string>;

export function DeleteCodexSession(arg1:string):Promise<void>;

export function DeleteCodexSessionBackup(arg1:string):Promise<string>;

export function ExportConfig():Promise<string>;

export function GenerateCodexConfigToml():Promise<string>;

export function GetAppConfig():Promise<main.AppConfig>;

export function GetAppVersion():Promise<string>;

export function GetCodexConfigPath():Promise<string>;

export function GetCodexSessionContent(arg1:string):Promise<main.SessionDetail>;

export function GetLogHistory(arg1:number):Promise<Array<main.LogEntry>>;

export function GetOverviewSnapshot():Promise<main.OverviewSnapshot>;

export function GetProxyStatus():Promise<main.ProxyStatusPayload>;

export function GetSandboxConfig():Promise<main.SandboxWorkspaceConfig>;

export function GetUsageBalance():Promise<main.UsageBalance>;

export function HasLegacySessions():Promise<boolean>;

export function ImportConfig(arg1:string):Promise<main.AppConfig>;

export function ListCodexConfigBackups():Promise<Array<string>>;

export function ListCodexSessionBackups():Promise<Array<string>>;

export function ListCodexSessionProviders():Promise<Array<string>>;

export function ListCodexSessions():Promise<Array<main.CodexSession>>;

export function MigrateCodexProviders(arg1:string,arg2:string):Promise<main.MigrationResult>;

export function ReadCodexConfigToml():Promise<string>;

export function RestartProxy():Promise<main.ProxyStatusPayload>;

export function RestoreCodexConfigToml():Promise<string>;

export function RestoreCodexConfigTomlFromBackup(arg1:string):Promise<string>;

export function RestoreCodexSessions(arg1:string):Promise<main.MigrationResult>;

export function RunHealthCheck():Promise<main.HealthCheckResult>;

export function SaveAppConfig(arg1:main.AppConfig):Promise<main.AppConfig>;

export function SetCurrentProfile(arg1:string):Promise<main.AppConfig>;

export function SetSandboxConfig(arg1:main.SandboxWorkspaceConfig):Promise<main.SandboxWorkspaceConfig>;

export function StartProxy():Promise<main.ProxyStatusPayload>;

export function StopProxy():Promise<main.ProxyStatusPayload>;

export function WriteCodexConfigToml():Promise<string>;

export function WriteCodexConfigTomlRaw(arg1:string):Promise<string>;
